First pass at `ste_vec` docs for JSONB containment indexing
cipherstash/encrypt-query-language pull request #9
Opened 2024-10-10 11:52 UTC by freshtonic

2024-10-10 13:36 UTC, auxesis requested changes
This is great to see @freshtonic. 

Have added some minor suggestions.

2024-10-10 13:36 UTC, auxesis commented on README.md
> +An ste_vec index on a encrypted JSONB column enables the use of Postgres's `@>` and `<@` containment operators.
Link to the Postgres documentation so users have more context
```suggestion
An ste_vec index on a encrypted JSONB column enables the use of PostgreSQL's `@>` and `<@` [containment operators](https://www.postgresql.org/docs/16/functions-json.html#FUNCTIONS-JSONB-OP-TABLE).
```

2024-10-10 13:36 UTC, auxesis commented on README.md
> +Within a dataset, encrypted columns indexed using an ste_vec that use different prefixes can never compare as equal and containment queries that manage to mix index terms from multiple columns will n
Line per sentence, to improve editability
```suggestion
Within a dataset, encrypted columns indexed using an ste_vec that use different prefixes can never compare as equal. 
Containment queries that manage to mix index terms from multiple columns will never return a positive result. 
This is by design.
```

2024-10-10 13:36 UTC, auxesis commented on README.md
> +The complete set of JSON types is supported by the indexer. Null values are ignored by the indexer.
Line per sentence, to improve editability

```suggestion
The complete set of JSON types is supported by the indexer. 
Null values are ignored by the indexer.
```

2024-10-10 22:56 UTC, freshtonic commented on README.md
> +An ste_vec index on a encrypted JSONB column enables the use of PostgreSQL's `@>` and `<@` [containment operators](https://www.postgresql.org/docs/16/functions-json.html#FUNCTIONS-JSONB-OP-TABLE).
Nice

2024-10-10 22:58 UTC, freshtonic commented
Looks like @calvinbrewer has actioned your suggestions already, @auxesis .

Let me know when this is good to merge.

2024-10-11 01:49 UTC, auxesis approved these changes
@freshtonic LGTM, :shipit:

2024-10-11 01:49 UTC, merged